/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import jooqdata.Contractregistry;
import jooqdata.Keys;
import jooqdata.tables.records.LotRecord;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lot extends TableImpl<LotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ContractRegistry.lot</code>
     */
    public static final Lot LOT = new Lot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LotRecord> getRecordType() {
        return LotRecord.class;
    }

    /**
     * The column <code>ContractRegistry.lot.lot_name</code>.
     */
    public final TableField<LotRecord, String> LOT_NAME = createField(DSL.name("lot_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>ContractRegistry.lot.customer_code</code>.
     */
    public final TableField<LotRecord, String> CUSTOMER_CODE = createField(DSL.name("customer_code"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>ContractRegistry.lot.price</code>.
     */
    public final TableField<LotRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>ContractRegistry.lot.currency_code</code>.
     */
    public final TableField<LotRecord, String> CURRENCY_CODE = createField(DSL.name("currency_code"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>ContractRegistry.lot.nds_rate</code>.
     */
    public final TableField<LotRecord, String> NDS_RATE = createField(DSL.name("nds_rate"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>ContractRegistry.lot.place_delivery</code>.
     */
    public final TableField<LotRecord, String> PLACE_DELIVERY = createField(DSL.name("place_delivery"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>ContractRegistry.lot.date_delivery</code>.
     */
    public final TableField<LotRecord, LocalDateTime> DATE_DELIVERY = createField(DSL.name("date_delivery"), SQLDataType.LOCALDATETIME(6), this, "");

    private Lot(Name alias, Table<LotRecord> aliased) {
        this(alias, aliased, null);
    }

    private Lot(Name alias, Table<LotRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ContractRegistry.lot</code> table reference
     */
    public Lot(String alias) {
        this(DSL.name(alias), LOT);
    }

    /**
     * Create an aliased <code>ContractRegistry.lot</code> table reference
     */
    public Lot(Name alias) {
        this(alias, LOT);
    }

    /**
     * Create a <code>ContractRegistry.lot</code> table reference
     */
    public Lot() {
        this(DSL.name("lot"), null);
    }

    public <O extends Record> Lot(Table<O> child, ForeignKey<O, LotRecord> key) {
        super(child, key, LOT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Contractregistry.CONTRACTREGISTRY;
    }

    @Override
    public UniqueKey<LotRecord> getPrimaryKey() {
        return Keys.LOT_PK;
    }

    @Override
    public List<ForeignKey<LotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LOT__LOT_CUSTOMER_FK);
    }

    private transient Customer _customer;

    /**
     * Get the implicit join path to the <code>ContractRegistry.customer</code>
     * table.
     */
    public Customer customer() {
        if (_customer == null)
            _customer = new Customer(this, Keys.LOT__LOT_CUSTOMER_FK);

        return _customer;
    }

    @Override
    public List<Check<LotRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("lot_currency_code_check"), "(((currency_code)::text = ANY ((ARRAY['RUB'::character varying, 'USD'::character varying, 'EUR'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("lot_nds_check_check"), "(((nds_rate)::text = ANY ((ARRAY['Без НДС'::character varying, '18%'::character varying, '20%'::character varying])::text[])))", true)
        );
    }

    @Override
    public Lot as(String alias) {
        return new Lot(DSL.name(alias), this);
    }

    @Override
    public Lot as(Name alias) {
        return new Lot(alias, this);
    }

    @Override
    public Lot as(Table<?> alias) {
        return new Lot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(String name) {
        return new Lot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Name name) {
        return new Lot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Table<?> name) {
        return new Lot(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, BigDecimal, String, String, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super String, ? super String, ? super BigDecimal, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super String, ? super String, ? super BigDecimal, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
