/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import java.util.Arrays;
import java.util.List;

import jooqdata.tables.Customer;
import jooqdata.tables.Lot;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contractregistry extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ContractRegistry</code>
     */
    public static final Contractregistry CONTRACTREGISTRY = new Contractregistry();

    /**
     * The table <code>ContractRegistry.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>ContractRegistry.lot</code>.
     */
    public final Lot LOT = Lot.LOT;

    /**
     * No further instances allowed
     */
    private Contractregistry() {
        super("ContractRegistry", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Customer.CUSTOMER,
            Lot.LOT
        );
    }
}
